export const Readers = [
  {
    id: 1,
    name: "Ms Aoife Kramer",
    rank: 10,
    company: "CompanyA",
    backImg: "https://source.unsplash.com/1600x900/?nature,water",
    proImg: "https://source.unsplash.com/1600x1600/?women,face",
    con: "Connect",
    location: "Helsinki",
  },
  {
    id: 2,
    name: "Saffron Lin",
    rank: 1,
    company: "CompanyB",
    backImg: "https://source.unsplash.com/1600x900/?nature,fire",
    proImg: "https://source.unsplash.com/1600x1600/?women,face",
    con: "Connect",
    location: "Stockholm",
  },
  {
    id: 3,
    name: "Osian Mcgee",
    rank: 3,
    company: "CompanyC",
    backImg: "https://source.unsplash.com/1600x900/?nature,forest",
    proImg: "https://source.unsplash.com/1600x1600/?people,face",
    con: "Connect",
    location: "Milan",
  },
  {
    id: 4,
    name: "Eva Krueger",
    rank: 44,
    company: "CompanyD",
    backImg: "https://source.unsplash.com/1600x900/?nature,sun",
    proImg: "https://source.unsplash.com/1600x1600/?women,face",
    con: "Connect",
    location: "Milan",
  },
  {
    id: 5,
    name: "Declan Arroyo",
    rank: 55,
    company: "CompanyE",
    backImg: "https://source.unsplash.com/1600x900/?nature,earth",
    proImg: "https://source.unsplash.com/1600x1600/?men,face",
    con: "Connect",
    location: "Stockholm",
  },
  {
    id: 6,
    name: "Declan Arroyo",
    rank: 6,
    company: "CompanyF",
    backImg: "https://source.unsplash.com/1600x900/?nature,wind",
    proImg: "https://source.unsplash.com/1600x1600/?people,face",
    con: "Connect",
    location: "Helsinki",
  },
];
