export const Readers = [
  {
    id: 1,
    name: "Ms Aoife Kramer",
    rank: 10,
    category: ["Education", "Science", "Fiction"],
    backImg: "https://source.unsplash.com/1600x900/?nature,water",
    proImg: "https://source.unsplash.com/1600x1600/?women,face",
    con: "Connect",
    location: "Helsinki",
  },
  {
    id: 2,
    name: "Saffron Lin",
    rank: 1,
    category: ["Education", "Science", "Fiction"],
    backImg: "https://source.unsplash.com/1600x900/?nature,fire",
    proImg: "https://source.unsplash.com/1600x1600/?women,face",
    con: "Connect",
    location: "Stockholm",
  },
  {
    id: 3,
    name: "Osian Mcgee",
    rank: 3,
    category: ["Education", "Science", "Fiction"],
    backImg: "https://source.unsplash.com/1600x900/?nature,forest",
    proImg: "https://source.unsplash.com/1600x1600/?man,face",
    con: "Connect",
    location: "Milan",
  },
  {
    id: 4,
    name: "Eva Krueger",
    rank: 44,
    category: ["Education", "Science", "Fiction"],
    backImg: "https://source.unsplash.com/1600x900/?nature,sun",
    proImg: "https://source.unsplash.com/1600x1600/?women,face",
    con: "Connect",
    location: "Milan",
  },
  {
    id: 5,
    name: "Declan Arroyo",
    rank: 55,
    category: ["Education", "Science", "Fiction"],
    backImg: "https://source.unsplash.com/1600x900/?nature,earth",
    proImg: "https://source.unsplash.com/1600x1600/?man,face",
    con: "Connect",
    location: "Stockholm",
  },
  {
    id: 6,
    name: "Rose Berge",
    rank: 6,
    category: ["Education", "Science", "Fiction"],
    backImg: "https://source.unsplash.com/1600x900/?nature,wind",
    proImg: "https://source.unsplash.com/1600x1600/?people,face",
    con: "Connect",
    location: "Helsinki",
  },
  {
    id: 7,
    name: "Declania Arro",
    rank: 6,
    category: ["Education", "Science", "Fiction"],
    backImg: "https://source.unsplash.com/1600x900/?nature,flower",
    proImg: "https://source.unsplash.com/1600x1600/?woman,face",
    con: "Connect",
    location: "Helsinki",
  },
  {
    id: 8,
    name: "Dec Arroyo",
    rank: 6,
    category: ["Education", "Science", "Non-Fiction"],
    backImg: "https://source.unsplash.com/1600x900/?nature,rock",
    proImg: "https://source.unsplash.com/1600x1600/?man,face",
    con: "Connect",
    location: "Helsinki",
  },
];
